name = "mosquitto"
description = "An Ada-binding to mosquitto https://mosquitto.org/"
version = "1.0.2"
website = "https://github.com/persan/mosquitto-ada"
authors = ["Per Sandberg <per.s.sandberg@bahnhof.se>"]
maintainers = ["Per Sandberg <per.s.sandberg@bahnhof.se>"]
maintainers-logins = ["persan"]
licenses = "MIT"
tags = ["binding", "mqtt"]

[gpr-externals]
  MOSQUITTO_PLATFORM = ["linux", "windows"]
  MOSQUITTO_MODE = ["debug", "release"]

[gpr-set-externals]
  BUILD_MODE = "release"


[[depends-on]]
  [depends-on.'case(os)'.linux]
    [depends-on.'case(distribution)'.'debian|ubuntu']
       libmosquitto   = "^1.0.0"
    [depends-on.'case(distribution)'.'fedora']
       libmosquitto = "^1.0.0"

[[actions]]
type = "test"
command = ["make", "-C" , "tests" ]
