name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install -y gnat gprbuild libmosquitto-dev
    - name: Build
      run: make compile

    - name: Test
      run: >
        sudo apt-get install -y  mosquitto  && 
        echo "127.0.0.1 mqtt" | sudo tee -a /etc/hosts && 
        sudo systemctl start mosquitto && 
        make test
